Improve output of mise project setup action

diff --git a/.github/actions/mise-project-setup/action.yaml b/.github/actions/mise-project-setup/action.yaml
--- a/.github/actions/mise-project-setup/action.yaml
+++ b/.github/actions/mise-project-setup/action.yaml
@@ -57,7 +57,6 @@ runs:
         ## Only use precompiled python binaries
         MISE_PYTHON_COMPILE: false
       run: |
-        set -x
         # Unset in case it is set by an earlier run of this action
         unset UV_PYTHON_DOWNLOADS
 
@@ -86,25 +85,30 @@ runs:
       env:
         DIRECTORIES: ${{ steps.init.outputs.mise-install-directories }}
       run: |
-        set -x
+        err=false
         for dir in $DIRECTORIES; do
           echo "::group::Ensure dependencies: $dir"
           pushd "$dir"
           mise ls --current
           count=$(mise ls --current --missing --no-header | wc -l)
           if [ $count -gt 0 ]; then
-            echo "Missing tools: $count"
-            exit 1
+            echo "::error::Count of missing tools: $count"
+            err=true
+          else
+            echo "Result of check: no missing tools"
           fi
           popd
           echo "::endgroup::"
         done
+
+        if [ "$err" = true ]; then
+          exit 1
+        fi
       shell: bash
 
     - name: Set final changes for rest of workflow
       run: |
-        echo ::group::Environment changes for rest of workflow
-        echo "Disable uv downloads with UV_PYTHON_DOWNLOADS=never"
-        echo "UV_PYTHON_DOWNLOADS=never" >> "$GITHUB_ENV"
+        echo "::group::Environment changes for rest of workflow"
+        echo "UV_PYTHON_DOWNLOADS=never" | tee -a "$GITHUB_ENV"
         echo "::endgroup::"
       shell: bash
