Improve output of mise project setup action (#64)
* Improve output of mise project setup action

* Remove duplicate `.` in mise install paths

* Improve output regarding names vs first line of run

diff --git a/.github/actions/mise-project-setup/action.yaml b/.github/actions/mise-project-setup/action.yaml
--- a/.github/actions/mise-project-setup/action.yaml
+++ b/.github/actions/mise-project-setup/action.yaml
@@ -13,14 +13,15 @@ runs:
   using: composite
   steps:
     - id: init
-      name: Prepare variables
 
       env:
         CACHE_MODE: ${{ inputs.cache-mode }}
         DIRECTORY: ${{ inputs.directory }}
         # renovate: datasource=github-releases depName=jdx/mise
         MISE_VERSION: v2025.8.13
-      run: "${GITHUB_ACTION_PATH}/init.sh"
+      run: |
+        # Initialize mise-project-setup action
+        "${GITHUB_ACTION_PATH}/init.sh"
       shell: bash
 
     - id: cache-restore
@@ -48,7 +49,6 @@ runs:
         working_directory: ${{ inputs.directory }}
 
     - if: steps.cache-restore.outputs.cache-hit != 'true'
-      name: Install tools
 
       env:
         DIRECTORIES: ${{ steps.init.outputs.mise-install-directories }}
@@ -57,7 +57,8 @@ runs:
         ## Only use precompiled python binaries
         MISE_PYTHON_COMPILE: false
       run: |
-        set -x
+        # Install mise tools
+
         # Unset in case it is set by an earlier run of this action
         unset UV_PYTHON_DOWNLOADS
 
@@ -81,30 +82,36 @@ runs:
         key: ${{ steps.cache-restore.outputs.cache-primary-key }}
         path: ${{ steps.init.outputs.cache-paths }}
 
-    - name: Ensure tools are installed properly
-
-      env:
+    - env:
         DIRECTORIES: ${{ steps.init.outputs.mise-install-directories }}
       run: |
-        set -x
+        # Ensure tools are installed properly
+
+        err=false
         for dir in $DIRECTORIES; do
           echo "::group::Ensure dependencies: $dir"
           pushd "$dir"
           mise ls --current
           count=$(mise ls --current --missing --no-header | wc -l)
           if [ $count -gt 0 ]; then
-            echo "Missing tools: $count"
-            exit 1
+            echo "::error::Count of missing tools: $count"
+            err=true
+          else
+            echo "Result of check: no missing tools"
           fi
           popd
           echo "::endgroup::"
         done
+
+        if [ "$err" = true ]; then
+          exit 1
+        fi
       shell: bash
 
-    - name: Set final changes for rest of workflow
-      run: |
-        echo ::group::Environment changes for rest of workflow
-        echo "Disable uv downloads with UV_PYTHON_DOWNLOADS=never"
-        echo "UV_PYTHON_DOWNLOADS=never" >> "$GITHUB_ENV"
+    - run: |
+        # Set final changes for rest of workflow
+
+        echo "::group::Environment changes for rest of workflow"
+        echo "UV_PYTHON_DOWNLOADS=never" | tee -a "$GITHUB_ENV"
         echo "::endgroup::"
       shell: bash
